steps:
# Build web_app Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/acoustical-web-app:latest', '-f', 'web_app/Dockerfile', '.']
  id: 'Build Web App Image'

# Push web_app Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/acoustical-web-app:latest']
  id: 'Push Web App Image'

# Deploy web_app to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'acoustical-web-app'
    - '--image=gcr.io/${PROJECT_ID}/acoustical-web-app:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--min-instances=0'
    - '--max-instances=1'
    - '--project=${PROJECT_ID}'
  id: 'Deploy Web App to Cloud Run'

# Build vertex_ai_chord_extractor Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/chord-extractor-essentia:v1', '-f', 'vertex_ai_chord_extractor/Dockerfile', '.']
  id: 'Build Essentia Predictor Image'

# Push vertex_ai_chord_extractor Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/chord-extractor-essentia:v1']
  id: 'Push Essentia Predictor Image'

# Upload model to Vertex AI (creates model if not exists, new version if exists)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'ai'
    - 'models'
    - 'upload'
    - '--display-name=chord-extractor-essentia'
    - '--container-image-uri=gcr.io/${PROJECT_ID}/chord-extractor-essentia:v1'
    - '--region=us-central1'
    - '--project=${PROJECT_ID}'
  id: 'Upload Essentia Model to Vertex AI'

# Deploy model to Vertex AI Endpoint
# NOTE: Replace YOUR_VERTEX_AI_ENDPOINT_ID with the actual Endpoint ID after creating it manually.
# Example: gcloud ai endpoints create --display-name=chord-extractor-essentia-endpoint --region=us-central1
# Then get the ID: gcloud ai endpoints list --region=us-central1 --filter="display_name=chord-extractor-essentia-endpoint"
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'ai'
    - 'endpoints'
    - 'deploy-model'
    - 'projects/${PROJECT_ID}/locations/us-central1/endpoints/3741309315345022976'
    - '--model=projects/640158882154/locations/us-central1/models/724132860495134720'
    - '--display-name=chord-extractor-essentia-endpoint'
    - '--machine-type=n1-standard-2'
    - '--min-replica-count=1'
    - '--max-replica-count=1'
    - '--project=${PROJECT_ID}'
  id: 'Deploy Essentia Predictor to Vertex AI'

images:
- 'gcr.io/${PROJECT_ID}/acoustical-web-app:latest'
- 'gcr.io/${PROJECT_ID}/chord-extractor-essentia:v1'
